# Setup
label: nashp.com
title: nash
url: https://nashpitre.github.io
paginate: 10
baseurl: ""
permalink: /:slug

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
include:
- _pages

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options
# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Nash Pitre
  url: https://twitter.com/nashp
  email: nashp@me.com

# Custom vars
version: 3.0.0

defaults:
  -
    scope:
      path: "_pages"
    values:
      layout: "page"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "_posts/blog"
    values:
      categories: "blog"
  -
    scope:
      path: "_posts/music"
    values:
      categories: "music"
  -
    scope:
      path: "_posts/photos"
    values:
      categories: "photos"
  -
    scope:
      path: "_posts/shop"
    values:
      categories: "shop"
  -
    scope:
      path: "_posts/video"
    values:
      categories: "video"
  -
    scope:
      path: "_posts/journal"
    values:
      categories: "journal"