# Setup
title: nashp.com
url: https://nashpitre.github.io
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
include:
- _pages

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

collections:
  projects:
    output: true
    permalink: /:collection/:title/

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Nash Pitre
  url: https://twitter.com/nashp
  email: nashp@me.com

# Custom vars
version: 3.0.0
